In [14]:
import pandas as pd
import glob as gb
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## File periodik

In [20]:
# regex semua file .csv wisatwan mancanegara
loc_1 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-jumlah-kunjungan-wisatawan-mancanegara*.csv'
filenames_1 = gb.glob(loc_1)

# regex semua file .csv wisatawan nusantara
loc_2 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-jumlah-kunjungan-wisatawan-nusantara*.csv'
filenames_2 = gb.glob(loc_2)

# regex semua file .csv statistik wisata per tahun
loc_3 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-jumlah-statistik-wisata*.csv'
filenames_3 = gb.glob(loc_3)

# regex semua file .csv kategori event
loc_4 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-kategori-event*.csv'
filenames_4 = gb.glob(loc_4)

# rata-rata lama menginap
loc_5 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-rata-rata-*.csv'
filenames_5 = gb.glob(loc_5)

In [22]:
# Pemanggilan file-file csv menggunakan list
#
# Wisatawan mancanegara
list_1 = []
for file_1 in filenames_1:
    df_1 = pd.read_csv(file_1)
    list_1.append(df_1)
wisatawan_mancanegara = pd.concat(list_1)

# Wisatawan nusantara
list_2 = []
for file_2 in filenames_2:
    df_2 = pd.read_csv(file_2)
    list_2.append(df_2)
wisatawan_nusantara = pd.concat(list_2)

# Statistik wisata
list_3 = []
for file_3 in filenames_3:
    df_3 = pd.read_csv(file_3)
    list_3.append(df_3)
statistik_wisata = pd.concat(list_3)

# Kategori event
list_4 = []
for file_4 in filenames_4:
    df_4 = pd.read_csv(file_4)
    list_4.append(df_4)
event_dki = pd.concat(list_4)

# Lama menginap
list_5 = []
for file_5 in filenames_5:
    df_5 = pd.read_csv(file_5)
    list_5.append(df_5)
lama_menginap = pd.concat(list_5)

In [23]:
# cek unique row
print(wisatawan_mancanegara['bulan'].unique())
print(wisatawan_nusantara['bulan'].unique())
print(statistik_wisata['tahun'].unique())
print(event_dki['tahun'].unique())
print(lama_menginap['tahun'].unique())
print(lama_menginap['bulan'].unique())

[ 8  4 12  2  1  7  6  3  5 11 10  9]
[ 8  4 12  2  1  6  3  5 11 10  9  7]
[2017 2018 2019]
[2016 2017 2018 2019]
[2016 2017 2018]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## File non-periodik

In [27]:
# jumlah hotel 
loc_6 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-jumlah-hotel-berbintang-dan-non-bintang-jakarta-tahun-2020.csv'
jumlah_hotel = pd.read_csv(loc_6)

# jumlah peserta pelatihan profesi kepariwisataan
loc_7 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-jumlah-peserta-pelatihan-profesi-kepariwisataan-di-provinsi-dki-jakarta-tahun-2019.csv'
jumlah_peserta_pelatihan = pd.read_csv(loc_7)

# jumlah usaha jasa pariwisata 2018
loc_7 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-jumlah-usaha-jasa-pariwisata-tahun-2018.csv'
jumlah_usaha_jasa_pariwisata = pd.read_csv(loc_7)

# jumlah usaha pariwisata bidang hiburan dan rekreasi
loc_8 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-jumlah-usaha-pariwisata-bidang-hiburan-dan-rekreasi-menurut-jenis-usaha-dan-kecamatan.csv'
jumlah_usaha_pariwisata_hiburan = pd.read_csv(loc_8)

# kunjungan wisata mancanegara 1995-2000
loc_9 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-kunjungan-wisata-mancanegara-ke-indonesia-menurut-pintu-masuk-tahun-1995-2000.csv'
kunjungan_mancanegara_keindonesia = pd.read_csv(loc_9)

# kunjungan wisata mancanegara ke dki januari tahun 2020
loc_9 = 'C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Pariwisata/\
data-kunjungan-wisatawan-mancanegara-ke-provinsi-dki-jakarta-bulan-januari-tahun-2020-melalui-2-pintu-masuk.csv'
kunjungan_mancanegara_kedki = pd.read_csv(loc_9)